### ISSUE TITLE
Node 16 Support for OSX M1 arm64

### ISSUE THREAD

**Issue by tzjames** [Prior99/native-image-diff#31]
I'm on an OSX M1.  When running `npm i native-image-diff` I get:
```
npm ERR! Downloading native-image-diff prebuilt binary from "https://github.com/Prior99/native-image-diff/releases/download/0.1.14/native-image-diff-darwin-arm64-93.node".
npm ERR! Error: No supported native-image-diff 0.1.14 build found for node v16.1.0 on darwin (arm64).
npm ERR!     at Request.<anonymous> (/xxx/node_modules/native-image-diff/scripts/install.js:38:19)
npm ERR!     at Request.emit (node:events:365:28)
npm ERR!     at Request.onRequestResponse (/xxx/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:365:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:487:22)
npm ERR!     at TLSSocket.emit (node:events:365:28)
npm ERR!     at addChunk (node:internal/streams/readable:314:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
```
Is there any work around?

**Comment by Prior99** [comment]
Sadly, no. There are no prebuilt binaries for that platform.

**Comment by tfactor2** [comment]
Still, any workarounds? Apple M1 becomes a very popular machine for development.

**Comment by tujoworker** [comment]
@Prior99 Could [pixelmatch](https://github.com/mapbox/pixelmatch) which uses [pngjs](https://github.com/lukeapage/pngjs) an option? 

Do you know more about these? What about speed? They do not use [libpng](https://github.com/glennrp/libpng). For me it seems that libpng is not maintained. A lot of PRs and issues over there. But no releases.

**Comment by Prior99** [comment]
@tfactor2 I am open for a PR adding some kind of CI support.
@tujoworker pixelmatch and pngjs indeed do not use libpng, which makes them slow. This was the whole idea behind creating this library. There is nothing wrong with switching to them, but you'd sacrifice around 10 times the performance (See [README](https://github.com/Prior99/native-image-diff#benchmark)).

I will not add support for a machine I do not own and use.
Apple makes it notoriously complicated to compile stuff for their hardware.
Sorry.

**Comment by svenstaro** [comment]
@Prior99 Any progress on this?

**Comment by Prior99** [comment]
@svenstaro I would be happy to accept a PR introducing some kind of CI support for this. I currently don't actively use this package and have no capacity to implement new features, especially if I don't have the hardware to test this.

**Comment by tfactor2** [comment]
@Prior99, could you point to a valid build pipeline, plz?
https://travis-ci.org/Prior99/native-image-diff doesn't work for me.
